import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:io';

import 'package:http/http.dart' as http;

Future<SepetModel> fetchSepet() async {
  final response = await http.get(
    Uri.parse('https://www.overdokids.com/sermobileboss/get_cart'),
    // Send authorization headers to the backend.
    headers: {
      HttpHeaders.authorizationHeader: '0ba108d95a36ef3228cbdb267ecddaf4',
    },
  );
  final responseJson = jsonDecode(response.body);

  if (response.statusCode == 200) {
    log('kod burada');
    print(response.statusCode);
  } else {
    print(response.statusCode);
  }

  return SepetModel.fromJson(responseJson);
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SepetModel {
/*
{
  "result": false,
  "message": "Auth Hatası. Lütfen çıkış yapıp tekrar giriş yapınız"
} 
*/

  bool? result;
  String? message;

  SepetModel({
    this.result,
    this.message,
  });
  SepetModel.fromJson(Map<String, dynamic> json) {
    result = json['result'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['message'] = message;
    return data;
  }
}
