///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SepetModel {
/*
{
  "result": false,
  "message": "Auth Hatası. Lütfen çıkış yapıp tekrar giriş yapınız"
} 
*/

  bool? result;
  String? message;

  SepetModel({
    this.result,
    this.message,
  });
  SepetModel.fromJson(Map<String, dynamic> json) {
    result = json['result'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['message'] = message;
    return data;
  }
}
